// name-picker/name-parts.js

export const baseAdjectives = ['Vibrant', 'Lazy', 'Cheerful', 'Quirky', 'Gentle', 'Bold', 'Shy', 'Clever'];
export const prismaticAdjectives = ['Radiant', 'Shimmering', 'Iridescent', 'Gleaming', 'Prismatic'];
export const neonAdjectives = ['Glowing', 'Electric', 'Buzzing', 'Pulsing', 'Flashing'];
export const cosmicAdjectives = ['Stellar', 'Astral', 'Luminous', 'Celestial', 'Galactic'];

export const baseColors = ['Amber','Amaranth','Amethyst','Apricot','Aqua','Aquamarine','Auburn','Azure','Aeige','Black','Blue','Bronze','Brown','Cardinal','Carmine','Celadon','Cerise','Cerulean','Charcoal','Chartreuse','Chocolate','Cinnamon','Copper','Coquelicot','Coral','Cream','Crimson','Cyan','Denim','Ebony','Ecru','Eggplant','Eggshell','Emerald','Fuchsia','Gold','Goldenrod','Gray','Green','Grey','Indigo','Ivory','Jade','Khaki','Lavender','Lemon','Lilac','Lime','Magenta','Mahogany','Maroon','Mauve','Mustard','Ocher','Olive','Orange','Orchid','Peach','Periwinkle','Persimmon','Pewter','Phlox','Pink','Puce','Pumpkin','Purple','Red','Rose','Ruby','Russet','Saffron','Salmon','Sapphire','Scarlet','Sepia','Shamrock','Sienna','Silver','Skobeloff','Slate','Tan','Tangerine','Taupe','Teal','Terracotta','Thistle','Topaz','Turquoise','Ultramarine','Umber','Vermilion','Violet','Viridian','Wheat','White','Wisteria','Yellow'];
export const baseColorHex = ['#FFBF00','#9F2B68','#9966cc','#FBCEB1','#00FFFF','#00FFBF','#E87722','#007FFF','#f5f5dc','#000000','#0000FF','#CD7F32','#A52A2A','#97233F','#960018','#ACE1AF','#DE3163','#2a52be','#36454F','#dfff00','#7B3F00','#D2691E','#B87333','#e50d0e','#FF7F50','#FFFDD0','#DC143C','#00FFFF','#6F8FAF','#555D50','#C2B280','#483248','#F0EAD6','#50C878','#FF00FF','#FFD700','#daa520','#808080','#00FF00','#808080','#4B0082','#FFFFF0','#00A36C','#F0E68C','#E6E6FA','#fff44f','#C8A2C8','#BFFF00','#FF00FF','#C04000','#800000','#e0b0ff','#FFDB58','#CC7722','#808000','#FFA500','#da70d6','#FFE5B4','#CCCCFF','#EC5800','#E9EAEC','#df00ff','#FFC0CB','#CC8899','#ff7518','#6a0dad','#FF0000','#FF007F','#E0115F','#80461B','#F4C430','#fa8072','#0f52ba','#FF2400','#704214','#009E60','#A0522D','#C0C0C0','#007474','#C0C2C9','#D2B48C','#F28500','#483C32','#008080','#e2725b','#D8BFD8','#ffc87c','#30D5C8','#4166f5','#826644','#E34234','#8F00FF','#40826D','#f5deb3','#fcfcfc','#BDB5D5','#FFFF00'];

export const prismaticColors = ['Blazing', 'Fiery', 'Scorching', 'Flaming', 'Burning', 'Ember', 'Infernal', 'Searing', 'Ignited', 'Torch', 'Icy', 'Frosty', 'Glacial', 'Chilly', 'Aqueous', 'Marine', 'Tidal', 'Oceanic', 'Dewy', 'Misty', 'Breezy', 'Windy', 'Gusty', 'Aerial', 'Zephyr', 'Stormy', 'Whirling', 'Drafty', 'Tempest', 'Cyclonic', 'Rocky', 'Stony', 'Earthen', 'Muddy', 'Clay', 'Sandy', 'Pebble', 'Craggy', 'Rugged', 'Boulder'];
export const prismaticColorHex = ['#FF0000', '#FF3300', '#FF5500', '#FF7700', '#FF9900', '#FFBB00', '#FFDD00', '#FFEE00', '#FFCC00', '#FFAA00', '#00FFFF', '#00E0E0', '#00C0C0', '#00A0A0', '#008080', '#006060', '#004040', '#002020', '#00B7EB', '#00CED1', '#87CEEB', '#ADD8E6', '#B0E0E6', '#87CEFA', '#B0C4DE', '#A1CAF1', '#89CFF0', '#73C2FB', '#5F9EA0', '#4682B4', '#00FF00', '#32CD32', '#228B22', '#006400', '#008000', '#2E8B57', '#3CB371', '#66CDAA', '#8FBC8F', '#20B2AA'];
export const prismaticEmojis = ['🔥','🔥','🔥','🔥','🔥','🔥','🔥','🔥','🔥','🔥','❄️','❄️','❄️','❄️','💧','💧','🌊','🌊','💦','💦','💨','💨','💨','🌬️','🌬️','🌪️','🌪️','🍃','🍃','🌬️','🌍','🪨','🪨','🌱','🌱','🌿','🌿','🌳','🌳','🍂'];

export const neonColors = ['Neon', 'Glow', 'Flux', 'Pulse', 'Spark'];
export const neonColorHex = ['#FF00FF', '#00FF00', '#FFFF00', '#FF4444', '#00FFFF'];

export const cosmicColors = ['Stellar', 'Nebula', 'Cosmo', 'Astral', 'Nova'];
export const cosmicColorHex = ['#4B0082', '#800080', '#000033', '#483D8B', '#9400D3'];

export const cosmicPrefixes = ['Jelly', 'Star', 'Moon', 'Crystal', 'Plasma'];
export const cosmicPrefixEmojis = ['🪼', '⭐', '🌙', '🔮', '⚡️'];

export const baseAnimals = ['Ant','Badger','Bat','Bear','Beaver','Beetle','Bird','Bison','Blowfish','Boar','Buffalo','Bug','Butterfly','Camel','Cat','Chicken','Chipmunk','Roach','Cow','Cow','Crab','Cricket','Crocodile','Deer','Dodo','Dog','Dolphin','Dove','Dragon','Duck','Eagle','Elephant','Fish','Flamingo','Fly','Fox','Frog','Giraffe','Goat','Gorilla','Hamster','Hedgehog','Hippopotamus','Honeybee','HoneyBadger','Horse','Kangaroo','Koala','Ladybug','Leopard','Lion','Lizard','Llama','Lobster','Mammoth','Microbe','Monkey','Mosquito','Mouse','Octopus','Orangutan','Otter','Owl','Ox','Panda','Parrot','Peacock','Penguin','Pig','Polar Bear','Poodle','Rabbit','Raccoon','Ram','Rat','Rhinoceros','Rock','Sauropod','Scorpion','Seal','Shark','Shrimp','Skunk','Sloth','Snail','Snake','Spider','Squid','Swan','Tiger','T-Rex','Turkey','Turtle','Unicorn','Whale','Wolf','Worm','Zebra'];
export const baseAnimalEmojis = ['🐜','🦡','🦇','🐻','🦫','🪲','🐦','🦬','🐡','🐗','🐃','🐛','🦋','🐫','🐈','🐔','🐿️','🪳','🐄','🐮','🦀','🦗','🐊','🦌','🦤','🐕','🐬','🕊️','🐉','🦆','🦅','🐘','🐟','🦩','🪰','🦊','🐸','🦒','🐐','🦍','🐹','🦔','🦛','🐝','🍯🦡','🐎','🦘','🐨','🐞','🐆','🦁','🦎','🦙','🦞','🦣','🦠','🐒','🦟','🐁','🐙','🦧','🦦','🦉','🐂','🐼','🦜','🦚','🐧','🐖','🐻‍❄️','🐩','🐇','🦝','🐏','🐀','🦏','🪨','🦕','🦂','🦭','🦈','🦐','🦨','🦥','🐌','🐍','🕷️','🦑','🦢','🐅','🦖','🦃','🐢','🦄','🐋','🐺','🪱','🦓'];

export const mythicalAnimals = ['Unicorn', 'Dragon', 'Phoenix', 'Dinosaur', 'Mermaid'];
export const mythicalAnimalEmojis = ['🦄', '🐉', '🐦‍🔥', '🦖', '🧜'];
export { mythicalAnimalEmojis as mythicalAnimalEmojisArray };
